version: '3.3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.api
    env_file:
      - .env
    restart: always
    ports:
      - '5000:5000'
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.web
    env_file:
      - .env
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
