version: '3.3'
services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile
  #   env_file:
  #     - .env.production
  #   restart: always
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - '5000:5000'
  #   networks:
  #     - app-network

  frontend:
    container_name: frontend
    image: slekup/cosy-co:main
    env_file:
      - .env.production
    restart: always
    ports:
      - '3000:3000'
    # depends_on:
    #   - backend
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./docker/production/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/production/ssl/:/etc/ssl/:ro
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      # - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
